<?php

function testmodule_menu() {
    $items = array();
    $items['content/nodecreator'] = array(
        'title' => 'Create new node.',
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('testmodule_nodecreator_form')
    );
    return $items;
}

function testmodule_nodecreator_form($node, &$form_state) {
    $form = array();
    $nodes = node_type_get_types();
    $form['node'] = array(
        '#type' => 'select',
        '#title' => t('Select node type'),
        '#options' => array(),
    );
    foreach ($nodes as $node) {
        $form['node']['#options'][$node->type] = $node->name;
    }
    $form['title'] = array(
        '#title' => t('Title'),
        '#type' => 'textfield',
        '#required' => TRUE,
    );
    $form['body'] = array(
        '#title' => t('Body'),
        '#type' => 'textarea',
        '#default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dui massa, euismod ut auctor non, suscipit a magna. Mauris hendrerit, ligula id placerat pellentesque, lectus erat ornare massa, id sodales lorem quam eu est. Vivamus mattis velit vel erat luctus a gravida ante iaculis. Aliquam sit amet arcu ut orci accumsan cursus quis gravida tortor. Proin sit amet lacus dolor. In lacinia ante a quam pellentesque at semper urna accumsan. Proin eu lectus nunc. Aenean sed diam at eros varius blandit. Donec at nunc non mi lacinia vehicula sed ut lacus. Curabitur id dolor eu enim rhoncus placerat. Lorem ipsum. ',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    return $form;
}
 
function testmodule_nodecreator_form_submit($form, &$form_state){
  $node = new stdClass();
  $node->type = $form_state['values']['node'];
  node_object_prepare($node);
 
  $node->title    = $form_state['values']['title'];
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value']   = $form_state['values']['body'];

  node_save($node);
  
  $form_state['redirect'] = 'node/' .$node->nid;
  drupal_set_message(t('New node created successfuly!'));
}